version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/uploads
    depends_on:
      - transcriber
    networks:
      - subtitle-net

  transcriber:
    build: ./transcriber
    ports:
      - "5001:5001"
    volumes:
      - ./uploads:/uploads
    networks:
      - subtitle-net

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - subtitle-net
    depends_on:
      - backend

networks:
  subtitle-net:
    driver: bridge
